POST http://localhost:3333/videos
Content-type: application/json

{
    "title":"video node",
    "description": "Este é o primeiro filme",
    "duration": 180
} 

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/
Content-type: application/json

{
    "title":"video02",
    "description": "Este é o primeiro filme",
    "duration": 180
} 

###

DELETE http://localhost:3333/videos/