POST https://mini-curso-nodejs-1.onrender.com/videos
Content-type: application/json

{
    "title":"video node",
    "description": "Este é o primeiro filme",
    "duration": 180
} 

###

GET https://mini-curso-nodejs-1.onrender.com/videos


###

PUT https://mini-curso-nodejs-1.onrender.com/videos/83bfe763-3cdd-43d7-8eb7-3e819382c206
Content-type: application/json

{
    "title":"video 250",
    "description": "Este é o primeiro filme",
    "duration": 180
} 

###

DELETE https://mini-curso-nodejs-1.onrender.com/videos/83bfe763-3cdd-43d7-8eb7-3e819382c206