POST https://mini-curso-nodejs-1.onrender.com/videos
Content-type: application/json

{
    "title":"video node",
    "description": "Este é o primeiro filme",
    "title":"video 163",
    "description": "Este é o de filme",
    "duration": 180
} 

###

GET https://mini-curso-nodejs-1.onrender.com/videos


###

PUT https://mini-curso-nodejs-1.onrender.com/videos/96a83bc7-5bcd-45c6-ba28-0833ab720362
Content-type: application/json

{
    "title":"video02",
    "title":"video13",
    "description": "Este é o primeiro filme",
    "duration": 180
} 

###

DELETE https://mini-curso-nodejs-1.onrender.com/videos/1b3f5d10-5520-46d7-8957-0e72d4351df5